# Generated by Django 5.2.9 on 2026-01-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_category_category_image_alter_blog_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="short_description",
            field=models.TextField(max_length=500, verbose_name="Short Description"),
        ),
    ]
